### PR TITLE
Fix (finally) bug with tooltips when multiple charts on one page.

### LINKED ISSUE #88: Tool tips not working when multiple charts used on a page
From the mailing list:

> I found smoothie charts and I'm trying to build an application that will use multiple charts in a dashboard.  An issue I have run into is being able to display a tool tip for each chart/graph.  The examples only show you how to use the following, but it only works for a single chart/graph.  Once a second chart/graph is added it breaks the tooltip on all the charts.  How can this be modified to work for multiple charts/graphs (like four)?
> 
> ```css
> div.smoothie-chart-tooltip {
>   background: #444;
>   padding: 1em;
>   margin-top: 20px;
>   font-family: consolas;
>   color: white;
>   font-size: 10px;
>   pointer-events: none;
> }
> ```

@Sly1024 have you observed this behaviour?

### PR DESCRIPTION
**Pull request by ralphwetzel**
Hi!
I as well encountered #88, yet #89 hasn't solved the issue for me.
Therefore I created this minor mod to fix #88 finally.

Best Regards, Ralph

### CODE REVIEW

**Comment by drewnoakes** [comment]
Looks good. Can you explain why you renamed the callback properties?

**Comment by ralphwetzel** [comment]
With the current implementation I've seen something best described as a scoping issue.

1) `mousemove` is used to name a **property** as well as a _function_.
2) `this.canvas.addEventListener('mousemove', this.mousemove);` was intended to provide the **property** as callback for the event. It yet provided the (raw) _function_.
3) As a result, when the event called the callback _function_ for the first time, `var el = this.getTooltipEl();` found no associated `this.tooltipEl` and created an additional one.
4) All the manipulations in `SmoothieChart.prototype.mousemove` were then affecting this wrongly created, additional tooltip item.

The easiest way - for me - to compensate for that misbehavior was to get rid of the potential ambiguity due to the scope by defining an explicit name for the callback **properties**.

**Comment by drewnoakes** [comment]
`mousemove` is a property, the value of which is a function. I don't believe there's any reason to rename it as such, though I might be missing something. Any issue around scoping likely applies to the value of `this`, which is why it we use `.bind(this)` when re-assigning it to itself.

The [`SmoothieChart.tooltipEl` to `this.tooltipEl`](https://github.com/joewalnes/smoothie/pull/96/files#diff-36a875e6e1e76bb259f024cb5903943dL567) change is definitely a bug fix though. I've merged that as 59521ce0edc724c126cb4bcb6f90c2b4fa114cb9.

If you believe there's still a bug, please provide a repro for it.

**Comment by ralphwetzel** [comment]
I am patching SmoothieChart ... and this definitely creates an issue with the scope of `this`.
Yet, as I found a way to solve this within my patch, there's no more need to alter your code.

**Pull request closed without merging**
